apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kib-manual
  name: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib-manual
  template:
    metadata:
      labels:
        app: kib-manual
    spec:
      containers:
      - image: kibana:7.8.0
        name: kibana
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        env:
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: ELASTICSEARCH_HOSTS
            value: http://es-service.default.svc.cluster.local:9200
        livenessProbe:
          httpGet:
            port: http
            path: /status
          initialDelaySeconds: 40
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kib-manual
  name: kibana-service
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kib-manual
  type: NodePort
